In [3]:
data = pd.read_csv("nba-players-data.csv")

# Drop rows with zero values
data = data[~(data == 0).any(axis=1)]

data_matrix = data.values 

# alternatives
m = data_matrix.shape[0]
# criterias
n = data_matrix.shape[1]

### get compare matrix from input file (only with low triangle)
compare_matrix = get_compare_matrix("weight.txt")
normalized_matrix = calculate_normalize_matrix(compare_matrix)

# sum of weight should be 1. weight for each criterion
weight_matrix = calculate_weight_matrix(normalized_matrix)
# print("weight for each criterion")
# print(weight_matrix)

# weighted sum
avg_weight_matrix = calculate_average_weight_matrix(compare_matrix, weight_matrix)
lamda = calculate_lamda(weight_matrix, avg_weight_matrix)
CI = calculate_CI(lamda, n)
RI = calculate_RI(n)
CR = calculate_CR(CI, RI)

# create and noralize alternative matrics
alternatives_matrices = get_alternative_matrics(n,m, data_matrix)
alternatives_norm_matrices = get_alternative_norm_matrics(alternatives_matrices)

# weight for each alternative with respect to each criteria
avg_weight_alternatives = get_avg_weight_alternatives(alternatives_norm_matrices)

# final score for each alternative
scores = np.dot(avg_weight_alternatives, weight_matrix)
# print("scores")
# print(scores)

NameError: name 'pd' is not defined

In [46]:
# display results
data['score'] = scores 
data.sort_values("score", ascending=False, inplace=True)
ranking = [(i+1) for i in range(len(scores))]
data['ranking'] = ranking
data.head(10)

     Python   Sql    ML  Tableau  Excel     score  ranking
14     0.88  0.83  0.93     0.19   0.63  0.008051        1
1      0.81  0.90  0.62     0.71   0.92  0.008034        2
89     0.70  0.82  0.92     0.52   0.93  0.008028        3
191    1.00  0.35  0.80     0.91   0.87  0.007860        4
70     0.84  0.58  0.96     0.44   0.75  0.007727        5
34     0.73  0.99  0.84     0.90   0.01  0.007705        6
198    0.60  0.99  0.66     0.71   0.93  0.007667        7
35     0.91  0.43  0.80     0.74   0.89  0.007628        8
197    0.95  0.65  0.62     0.74   0.61  0.007571        9
144    0.84  0.91  0.91     0.05   0.26  0.007541       10

In [46]:
# CR < 0.1 means good consistancy
weight_matrix, CR

(array([[0.33466316],
        [0.23763233],
        [0.23942507],
        [0.08723722],
        [0.10104222]]),
 array([0.06782994]))